#!/usr/bin/env bash
# bash script printing our domains and subdomains according to certain circumstances
display_info() {
    domain=$1
    subdomain=$2

    # Default subdomains
    default_subdomains=("www" "lb-01" "web-01" "web-02")

    # If subdomain parameter is not provided, use default subdomains
    if [ -z "$subdomain" ]; then
        for sub in "${default_subdomains[@]}"; do
            record_type=$(dig "$sub.$domain" | awk 'NR==13 {print $4}')
            # record_type=$(dig +short -t A "$sub.$domain" | awk '{print length($0) ? "A" : "CNAME"}')
            destination=$(dig +short -t A "$sub.$domain")
            echo "The subdomain $sub is a $record_type record and points to $destination"
        done
    else
        # If both domain and subdomain parameters are provided, display information for the specified subdomain
        record_type=$(dig +short -t A "$subdomain.$domain" | awk '{print length($0) ? "A" : "CNAME"}')
        destination=$(dig +short -t A "$subdomain.$domain")
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
} 

display_info "$1" "$2"
