#!/usr/bin/env bash
# 	installing nginx to listen at port 80
# 	query nginx with GET to return page containing hello world

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
# Configure Nginx to listen on port 80
# sed -i 's/80 default_server;/80;/g' /etc/nginx/sites-available/default

# Create a default HTML page
echo "Hello World" | sudo tee /var/www/html/index.html

# Restart Nginx using alternative method
sudo /etc/init.d/nginx restart
