#!/usr/bin/env bash
# 	installing nginx to listen at port 80
# 	used for redirection by altering redirection file

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx
# adjust firewall to allow http traffic
sudo ufw allow 'Nginx HTTP'
# start service
sudo service nginx start
# Configuration for redirection
string=$'\tserver_name _;\n\tlocation / {\n\t\trewrite https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}'
sed -i "s#server_name _;#$string#" /etc/nginx/sites-available/default

# Reload Nginx service
sudo service nginx reload
echo "$string"
