#!/usr/bin/env bash
# 	installing nginx to listen at port 80
# 	used for redirection by altering redirection file

# Install Nginx
apt-get update
apt-get install -y nginx

echo '
server {
    listen 80;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
' > /etc/nginx/sites-available/redirect_me

# Enable the configuration snippet by creating a symbolic link
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/

# Restart Nginx using alternative method (sending HUP signal)
sudo /etc/init.d/nginx restart
