#!/usr/bin/env bash
# 	installing nginx to listen at port 80
# 	used for set error 404

# Install Nginx
apt-get update
apt-get install -y nginx

# Create a custom 404 error page
echo "<!DOCTYPE html>
<html>
<head>
    <title>404 Not Found</title>
</head>
<body>
    <h1>404 Not Found</h1>
    <p>Ceci n\'est pas une page.</p>
</body>
</html>" > /usr/share/nginx/html/404.html

# Update the Nginx configuration to use the custom 404 page
sed -i '/^http {/a \    error_page 404 /404.html;' /etc/nginx/nginx.conf

# Restart Nginx using alternative method
sudo /etc/init.d/nginx restart
