#!/usr/bin/env bash
# display numbers 1 - 20 with additional output statements in specific iterations

i=1

while [ "$i" -lt 21 ]
do
	case "$i" in
		4)
			echo "$i"
			echo "bad luck from China"
			;;
		9)
			echo "$i"
			echo "bad luck from Japan"
			;;
		17)
			echo "$i"
			echo "bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac
	(( i++ ))
done
