#!/usr/bin/env bash
# checks file existence, type and size

file="school"

if [ -e "$file" ] && [ -d "$file" ];
then
	echo "school file exists"


	if [ -s "$file" ];
	then
		echo "school file is not empty"
	else
		echo "file is empty"
	fi

	if [ -f "$file" ];
	then
		echo "school is a regular file"
	fi

else
	echo "file does not exist"
fi
