#!/usr/bin/env bash

# Update Nginx configuration to run as nginx user and listen on port 8080
sed -i 's/user  nginx;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen       80;/listen       8080;/g' /etc/nginx/conf.d/default.conf

# Ensure the nginx user owns the necessary directories
chown -R nginx:nginx /var/lib/nginx
chown -R nginx:nginx /var/log/nginx
chown -R nginx:nginx /var/cache/nginx

# Start Nginx service
nginx -g 'daemon off;'
